# docker-compose.deploy.yml
version: '3.8'

volumes:
  userdb_vol:
  productdb_vol:
  orderdb_vol:

networks:
  micro_network:
    external:
      name: micro_network

services:
  user-api:
    container_name: cuser-service
    build:
      context: ../user-service-1
    ports:
    - "5001:5001"
    depends_on:
      - user-db
    networks:
      - micro_network
    restart: always

  user-db:
    container_name: cuser_dbase
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: Mango42
      POSTGRES_DB: user
    networks:
      - micro_network
    volumes:
    - userdb_vol:/var/lib/postgresql/data
    - ./initdb-user.sql:/docker-entrypoint-initdb.d/initdb-user.sql

  product-api:
    container_name: cproduct-service
    build:
      context: ../product-service-2
    ports:
    - "5002:5002"
    depends_on:
      - product-db
    networks:
      - micro_network
    restart: always

  product-db:
    container_name: cproduct_dbase
    image: postgres:latest
    ports:
    - "5433:5432"
    environment:
      POSTGRES_USER: postgres2
      POSTGRES_PASSWORD: Mango43
      POSTGRES_DB: product
    networks:
      - micro_network
    volumes:
    - productdb_vol:/var/lib/postgresql/data
    - ./initdb-product.sql:/docker-entrypoint-initdb.d/initdb-product.sql


  order-api:
    container_name: corder-service
    build:
      context: ../order-service-3
    ports:
    - "5003:5003"
    depends_on:
      - order-db
    networks:
      - micro_network
    restart: always

  order-db:
    container_name: corder_dbase
    image: postgres:latest
    ports:
    - "5434:5432"
    environment:
      POSTGRES_USER: postgres3
      POSTGRES_PASSWORD: Mango44
      POSTGRES_DB: order
    networks:
      - micro_network
    volumes:
    - orderdb_vol:/var/lib/postgresql/data
    - ./initdb-order.sql:/docker-entrypoint-initdb.d/initdb-order.sql

  frontend-app:
    container_name: cfrontend-app
    build:
      context: .
    ports:
    - "5000:5000"
    networks:
      - micro_network
    restart: always